### PR TITLE
Node 12/Electron 9 support

### PR DESCRIPTION
**Pull request by vyunikov**
This pull request tries to fix Node 12 and Electron 9 issues (#118 ).
Generally it uses forks of several dependencies: `ref` (`ref-napi`), `ref-struct` (`ref-struct-napi`), `node-ffi` (`ffi-napi`). 
`function-class` dependency refers to a pull request now as this PR has a fix for Node 12 compatibility issues.
Besides that there is another fix for a crash

### CODE REVIEW

**Comment by hisnameisjimmy** [comment]
Is there anyone around anymore to merge this?

**Comment by tom-james-watson** [comment]
If you work out what the most recent version of node that is compatible is then please let us know!

**Comment by aabuhijleh** [comment]
When I install this `npm i git+https://github.com/sixtydigits/NodObjC.git`

I get this build error

```
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:11:24: error: use of undeclared identifier 'napi_get_instance_data'
  napi_status status = napi_get_instance_data(env, &d);
                       ^
../src/ffi.cc:347:24: error: use of undeclared identifier 'napi_set_instance_data'
  napi_status status = napi_set_instance_data(
                       ^
2 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
```

I have node v12.5.0 installed

**Comment by vyunikov** [comment]
> When I install this `npm i git+https://github.com/sixtydigits/NodObjC.git`
> 
> I get this build error
> 
> ```
>   CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
> ../src/ffi.cc:11:24: error: use of undeclared identifier 'napi_get_instance_data'
>   napi_status status = napi_get_instance_data(env, &d);
>                        ^
> ../src/ffi.cc:347:24: error: use of undeclared identifier 'napi_set_instance_data'
>   napi_status status = napi_set_instance_data(
>                        ^
> 2 errors generated.
> make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
> gyp ERR! build error 
> ```
> 
> I have node v12.5.0 installed

APIs that compiler complains about were only introduced in node v12.8:
https://nodejs.org/api/n-api.html#n_api_napi_get_instance_data

That's why it won't build on an older versions unfortunately.

**Comment by vyunikov** [comment]
Also based on the logs from CI, this PR breaks backward compatibility with older node versions (specifically it fails to build with node v10). So it's more a questions to an author whether it makes sense to support that old versions of node

**Comment by sn-10-09** [comment]
In our electron app, (Running on macOS 10.15, node 12.18.3, electron 11)  we need a callback from the mac.framework to electron with arguments in the callback function. On doing this, using this PR, we get a crash with the following error :  
Exception Type: EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY
Termination Signal: Illegal instruction: 4

I have created a sample repo to reproduce this issue : [https://github.com/sn-10-09/electron11-nodobjc-test]
Note: A callback with no arguments runs successfully.
Any help on this would be really appreciated!

**Pull request closed without merging**
